version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  websvr:
    build: ./work
    container_name: web4mongo
    restart: unless-stopped
    volumes:
      - ./work/src:/var/www/html
    ports:
      - 80:80
    links:
      - mongo
    depends_on:
      - mongo

#usefule for debug, but be careful if used in production
#  mongo-express:
#    image: mongo-express
#    container_name: mongoex
#    ports:
#      - 8081:8081     
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
#      ME_CONFIG_MONGODB_URL: mongodb://root:mongopwd@mongo:27017/
#    links:
#      - mongo
#    depends_on:
#      - mongo
